<?php

namespace Database\Seeders;

use App\Models\Pegawai;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class PegawaiSeeder extends Seeder
{
    public function run(): void
    {
        $pegawaiSamples = [
            [
                'nama' => 'Rizki Ananda',
                'nik' => '1809031504890001',
                'nip' => '197901012010041001',
                'jabatan' => 'Sekretaris Desa',
                'email' => 'rizki.ananda@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5601',
                'status' => 'Aktif',
                'tempat_lahir' => 'Tanjung Kesuma',
                'tanggal_lahir' => '1989-04-15',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Dusun Sri Rejeki RT 01/RW 01, Desa Tanjung Kesuma',
                'masa_jabatan_mulai' => '2021-01-10',
                'universitas' => 'Universitas Lampung',
                'pendidikan_terakhir' => 'S1 Administrasi Publik',
                'tahun_lulus' => '2011',
                'sertifikat_pelatihan' => 'Pelatihan Tata Pemerintahan Desa 2023',
                'bahasa' => 'Indonesia, Inggris',
                'last_login' => Carbon::parse('2025-11-05 08:15:00'),
            ],
            [
                'nama' => 'Maya Pratiwi',
                'nik' => '1809032809900002',
                'nip' => '198909282011042002',
                'jabatan' => 'Kaur Keuangan',
                'email' => 'maya.pratiwi@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5602',
                'status' => 'Aktif',
                'tempat_lahir' => 'Metro',
                'tanggal_lahir' => '1990-09-28',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Jl. Cendana No. 8, Desa Tanjung Kesuma',
                'masa_jabatan_mulai' => '2019-05-14',
                'universitas' => 'Institut Pemerintahan Dalam Negeri',
                'pendidikan_terakhir' => 'S1 Keuangan Publik',
                'tahun_lulus' => '2012',
                'sertifikat_pelatihan' => 'Pelatihan Akuntansi Desa 2024',
                'bahasa' => 'Indonesia',
                'last_login' => Carbon::parse('2025-11-04 09:10:00'),
            ],
            [
                'nama' => 'Yoga Prakoso',
                'nik' => '1809030202920009',
                'nip' => '199202092014041009',
                'jabatan' => 'Operator Data',
                'email' => 'yoga.prakoso@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5609',
                'status' => 'Cuti',
                'tempat_lahir' => 'Metro',
                'tanggal_lahir' => '1992-02-09',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Kristen',
                'alamat' => 'Perumahan Tirta Asri Blok B2, Metro',
                'masa_jabatan_mulai' => '2021-03-15',
                'universitas' => 'Universitas Negeri Yogyakarta',
                'pendidikan_terakhir' => 'S1 Teknik Informatika',
                'tahun_lulus' => '2014',
                'sertifikat_pelatihan' => 'Pelatihan Sistem Informasi Desa, 2020',
                'bahasa' => 'Indonesia, Inggris',
                'last_login' => Carbon::parse('2025-10-27 14:25:00'),
            ],
            [
                'nama' => 'Bagus Ramdhan',
                'nik' => '1809031802910003',
                'nip' => '198902182012041003',
                'jabatan' => 'Kaur Perencanaan',
                'email' => 'bagus.ramdhan@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5603',
                'status' => 'Aktif',
                'tempat_lahir' => 'Tanjung Kesuma',
                'tanggal_lahir' => '1991-02-18',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Dusun Sumber Makmur RT 02/RW 02',
                'masa_jabatan_mulai' => '2020-02-01',
                'universitas' => 'Universitas Andalas',
                'pendidikan_terakhir' => 'S1 Perencanaan Wilayah',
                'tahun_lulus' => '2013',
                'sertifikat_pelatihan' => 'Workshop Smart Village 2022',
                'bahasa' => 'Indonesia',
            ],
            [
                'nama' => 'Dewi Kartika',
                'nik' => '1809030307880004',
                'nip' => '198807032010042004',
                'jabatan' => 'Kepala Dusun I',
                'email' => 'dewi.kartika@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5604',
                'status' => 'Aktif',
                'tempat_lahir' => 'Bandar Lampung',
                'tanggal_lahir' => '1988-07-03',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Dusun Tanjung Baru RT 03/RW 03',
                'masa_jabatan_mulai' => '2018-07-01',
                'universitas' => 'Universitas Terbuka',
                'pendidikan_terakhir' => 'S1 Ilmu Pemerintahan',
                'tahun_lulus' => '2010',
                'sertifikat_pelatihan' => 'Lokakarya Pemberdayaan Masyarakat 2021',
                'bahasa' => 'Indonesia',
            ],
            [
                'nama' => 'Arman Saputra',
                'nik' => '1809032211870005',
                'nip' => '198711222009041005',
                'jabatan' => 'Kepala Dusun II',
                'email' => 'arman.saputra@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5605',
                'status' => 'Aktif',
                'tempat_lahir' => 'Metro',
                'tanggal_lahir' => '1987-11-22',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Dusun Tri Rahayu RT 04/RW 04',
                'masa_jabatan_mulai' => '2017-04-12',
                'universitas' => 'Politeknik Negeri Lampung',
                'pendidikan_terakhir' => 'D3 Administrasi Bisnis',
                'tahun_lulus' => '2008',
                'sertifikat_pelatihan' => 'Bimbingan Teknis Aparatur 2022',
                'bahasa' => 'Indonesia',
            ],
            [
                'nama' => 'Laras Salsabila',
                'nik' => '1809031205930006',
                'nip' => '199312052014042006',
                'jabatan' => 'Kepala Dusun III',
                'email' => 'laras.salsabila@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5606',
                'status' => 'Tidak Aktif',
                'tempat_lahir' => 'Tanjung Kesuma',
                'tanggal_lahir' => '1993-12-05',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Dusun Wana Sejati RT 05/RW 05',
                'masa_jabatan_mulai' => '2016-09-01',
                'masa_jabatan_selesai' => '2024-06-30',
                'universitas' => 'Universitas Padjadjaran',
                'pendidikan_terakhir' => 'S1 Sosiologi',
                'tahun_lulus' => '2015',
                'sertifikat_pelatihan' => 'Pelatihan Kepemimpinan Aparatur 2019',
                'bahasa' => 'Indonesia, Inggris',
            ],
            [
                'nama' => 'Farhan Nugraha',
                'nik' => '1809031703950007',
                'nip' => '199503172018041007',
                'jabatan' => 'Staf Pelayanan',
                'email' => 'farhan.nugraha@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5607',
                'status' => 'Aktif',
                'tempat_lahir' => 'Metro',
                'tanggal_lahir' => '1995-03-17',
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'alamat' => 'Jl. Flamboyan No. 10, Desa Tanjung Kesuma',
                'masa_jabatan_mulai' => '2022-02-01',
                'universitas' => 'Universitas Negeri Malang',
                'pendidikan_terakhir' => 'S1 Administrasi Publik',
                'tahun_lulus' => '2017',
                'sertifikat_pelatihan' => 'Pelayanan Prima Desa 2023',
                'bahasa' => 'Indonesia',
            ],
            [
                'nama' => 'Kirana Ayu',
                'nik' => '1809032008960008',
                'nip' => '199608202019042008',
                'jabatan' => 'Staf Administrasi',
                'email' => 'kirana.ayu@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5608',
                'status' => 'Aktif',
                'tempat_lahir' => 'Tanjung Kesuma',
                'tanggal_lahir' => '1996-08-20',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Dusun Mekar Sari, Desa Tanjung Kesuma',
                'masa_jabatan_mulai' => '2024-01-05',
                'universitas' => 'Institut Pemerintahan Dalam Negeri',
                'pendidikan_terakhir' => 'S1 Pemerintahan',
                'tahun_lulus' => '2019',
                'sertifikat_pelatihan' => 'Pelatihan Administrasi Publik 2021',
                'bahasa' => 'Indonesia, Inggris',
            ],
            [
                'nama' => 'Sinta Rahayu',
                'nik' => '1809033005900010',
                'nip' => '199005302012041010',
                'jabatan' => 'Bendahara BUMDes',
                'email' => 'sinta.rahayu@tanjungkesuma.id',
                'nomor_hp' => '0812-1234-5610',
                'status' => 'Aktif',
                'tempat_lahir' => 'Bandar Lampung',
                'tanggal_lahir' => '1990-05-30',
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'alamat' => 'Dusun Sejahtera Indah RT 06/RW 02',
                'masa_jabatan_mulai' => '2023-03-01',
                'universitas' => 'Universitas Brawijaya',
                'pendidikan_terakhir' => 'S1 Akuntansi',
                'tahun_lulus' => '2012',
                'sertifikat_pelatihan' => 'Pelatihan Pengelolaan Keuangan Desa 2024',
                'bahasa' => 'Indonesia',
            ],
        ];

        foreach ($pegawaiSamples as $sample) {
            Pegawai::updateOrCreate(
                ['nik' => $sample['nik']],
                $sample
            );
        }
    }
}
