-- Struktur tabel pegawais yang sesuai dengan kebutuhan aplikasi
CREATE TABLE `pegawais` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `nama` VARCHAR(255) NOT NULL,
    `nik` VARCHAR(20) NOT NULL UNIQUE,
    `nip` VARCHAR(20) DEFAULT NULL,
    `jabatan` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `nomor_hp` VARCHAR(20) NOT NULL,
    `status` ENUM('Aktif', 'Cuti', 'Pensiun', 'Tidak Aktif') NOT NULL DEFAULT 'Aktif',
    `gambar` VARCHAR(255) DEFAULT NULL,
    `tempat_lahir` VARCHAR(255) DEFAULT NULL,
    `tanggal_lahir` DATE DEFAULT NULL,
    `jenis_kelamin` ENUM('Laki-laki', 'Perempuan') DEFAULT NULL,
    `agama` VARCHAR(100) DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `foto_ktp` VARCHAR(255) DEFAULT NULL,
    `sk_pengangkatan` VARCHAR(255) DEFAULT NULL,
    `sk_pemberhentian` VARCHAR(255) DEFAULT NULL,
    `masa_jabatan_mulai` DATE DEFAULT NULL,
    `masa_jabatan_selesai` DATE DEFAULT NULL,
    `universitas` VARCHAR(255) DEFAULT NULL,
    `pendidikan_terakhir` VARCHAR(255) DEFAULT NULL,
    `tahun_lulus` CHAR(4) DEFAULT NULL,
    `sertifikat_pelatihan` TEXT DEFAULT NULL,
    `bahasa` VARCHAR(255) DEFAULT NULL,
    `last_login` DATETIME DEFAULT NULL,
    `created_by` BIGINT UNSIGNED DEFAULT NULL,
    `updated_by` BIGINT UNSIGNED DEFAULT NULL,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `pegawais_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
    CONSTRAINT `pegawais_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Contoh data awal
INSERT INTO `pegawais` (
    `nama`, `nik`, `nip`, `jabatan`, `email`, `nomor_hp`, `status`,
    `tempat_lahir`, `tanggal_lahir`, `jenis_kelamin`, `agama`, `alamat`,
    `masa_jabatan_mulai`, `universitas`, `pendidikan_terakhir`, `tahun_lulus`,
    `sertifikat_pelatihan`, `bahasa`, `last_login`, `created_at`, `updated_at`
) VALUES
    (
        'Dani',
        '1871234567890002',
        '197806152023041001',
        'Administrasi Desa',
        'dani@desatanjung.com',
        '086005254002',
        'Aktif',
        'Metro',
        '1995-06-15',
        'Laki-laki',
        'Islam',
        'Jl. Melati No. 5, Desa Tanjung Kesuma',
        '2023-04-01',
        'Universitas Lampung',
        'S1 Administrasi Negara',
        '2018',
        'Pelatihan Tata Naskah Dinas, 2022',
        'Indonesia, Inggris',
        '2025-10-09 13:00:00',
        NOW(),
        NOW()
    ),
    (
        'Kirana Ayu',
        '1871234567890003',
        '197806152023041002',
        'Staf Administrasi',
        'kirana.ayu@tanjungkesuma.id',
        '0812-1234-5608',
        'Aktif',
        'Tanjung Kesuma',
        '1996-08-20',
        'Perempuan',
        'Islam',
        'Dusun Mekar Sari, Desa Tanjung Kesuma',
        '2024-01-05',
        'Institut Pemerintahan Dalam Negeri',
        'S1 Pemerintahan',
        '2019',
        'Pelatihan Administrasi Publik, 2021',
        'Indonesia, Inggris',
        NULL,
        NOW(),
        NOW()
    ),
    (
        'Yoga Prakoso',
        '1871234567890004',
        '197806152023041003',
        'Operator Data',
        'yoga.prakoso@tanjungkesuma.id',
        '0812-1234-5609',
        'Cuti',
        'Metro',
        '1992-02-09',
        'Laki-laki',
        'Kristen',
        'Perumahan Tirta Asri Blok B2, Metro',
        '2021-03-15',
        'Universitas Negeri Yogyakarta',
        'S1 Teknik Informatika',
        '2014',
        'Pelatihan Sistem Informasi Desa, 2020',
        'Indonesia, Inggris',
        NULL,
        NOW(),
        NOW()
    );

